### PR TITLE
nvim: add new BufferChangedTick(nvim_buf_get_changedtick) function

### PR DESCRIPTION
**Pull request by zchee**
Neovim has been added new `nvim_buf_get_changedtick` API.

The function's order and godoc comment conformed to Neovim's `api/buffer.c` file.

### CODE REVIEW

**Comment by zchee** [comment]
@garyburd Ah, I thought same thing.
But like `nvim_buf_line_count` is "line" "count", which separated with `_`. However `nvim_buf_get_changedtick` is not separated. So I write `BufferChangedtick`.
Should I fix to `BufferChangedtick`?

**Comment by garyburd** [comment]
Yeah, there are reasons to name it `BufferChangedtick`.  

After more thought, I think it should be renamed to `BufferChangedTick`.  This is what Go programmers expect.

**Comment by zchee** [comment]
@garyburd I totally agreed your opinion :)
Done.

**Comment by garyburd** [comment]
I think the definition should be:

    func BufferChangedTick(buffer Buffer) int {
 	    name(nvim_buf_get_changedtick)
    }

**Comment by zchee** [comment]
@garyburd Ah, correct... Sorry :(
Done.

**Pull request merged**
