### PR TITLE
Implements neovim/neovim@9d77a07 APIs

### PR DESCRIPTION
**Pull request by zchee**
Implements neovim/neovim@9d77a07 APIs.

compare is here:

```
> nvim_buf_clear_namespace(buffer Buffer, ns_id Integer, line_start Integer, line_end Integer) void { name(nvim_buf_clear_namespace) }
> nvim_buf_get_offset(buffer Buffer, index Integer) Integer { name(nvim_buf_get_offset) }
> nvim_buf_set_virtual_text(buffer Buffer, ns_id Integer, line Integer, chunks Array, opts Dictionary) Integer { name(nvim_buf_set_virtual_text) }
> nvim_create_buf(listed Boolean, scratch Boolean) Buffer { name(nvim_create_buf) }
> nvim_create_namespace(name String) Integer { name(nvim_create_namespace) }
> nvim_get_namespaces() Dictionary { name(nvim_get_namespaces) }
> nvim_input_mouse(button String, action String, modifier String, grid Integer, row Integer, col Integer) void { name(nvim_input_mouse) }
> nvim_open_win(buffer Buffer, enter Boolean, config Dictionary) Window { name(nvim_open_win) }
> nvim_select_popupmenu_item(item Integer, insert Boolean, finish Boolean, opts Dictionary) void { name(nvim_select_popupmenu_item) }
> nvim_set_vvar(name String, value Object) void { name(nvim_set_vvar) }
> nvim_ui_try_resize_grid(grid Integer, width Integer, height Integer) void { name(nvim_ui_try_resize_grid) }
> nvim_win_close(window Window, force Boolean) void { name(nvim_win_close) }
> nvim_win_get_config(window Window) Dictionary { name(nvim_win_get_config) }
> nvim_win_set_buf(window Window, buffer Buffer) void { name(nvim_win_set_buf) }
> nvim_win_set_config(window Window, config Dictionary) void { name(nvim_win_set_config) }
----
< nvim_set_client_info(name String, version Dictionary, typ String, methods map[string]*ClientMethod, attributes Dictionary) void { name(nvim_set_client_info) }
> nvim_set_client_info(name String, version Dictionary, type String, methods Dictionary, attributes Dictionary) void { name(nvim_set_client_info) }
```

Note that `nvim_set_client_info` diff is only of `typ` arg, `type` is Go reserve word.

---

If you find a doc that is not appropriate, please give a line comment. (Note that I know different to the latest nvim doc/*.txt document comment.)
I will fix this PR, Or there are also inappropriate comments in other places, so I will fix it in the next PR.

### CODE REVIEW

**Comment by justinmk** [comment]
> If you find a doc that is not appropriate, please give a line comment. (Note that I know different to the latest nvim doc/*.txt document comment.)

I would just wait until it can be automated as [discussed](https://github.com/neovim/go-client/pull/46#issuecomment-489981168).

**Comment by justinmk** [comment]
> Note that `nvim_set_client_info` diff is only of `typ` arg, `type` is Go reserve word.

what about `type_` instead?

**Comment by zchee** [comment]
> what about type_ instead?

it's Go idiom. basically, Go doesn't use underscore for variable, package name.
See https://github.com/golang/tools/blob/a434f64ace81347eff0fb4a32bc80a235e0ad762/go/pointer/query.go#L36

**Comment by zchee** [comment]
@justinmk 

> I would just wait until it can be automated as discussed.

Yes, I mean Please point out any obvious mistakes if there. such as _a Nvim_ ?

**Comment by zchee** [comment]
for note:
> it's Go idiom. basically, Go doesn't use underscore for variable, package name.

expect `.go` filename.

**Comment by justinmk** [comment]
LGTM. which parts of this are auto-generated? 

Is the auto-generator process documented anywhere? One or two lines with a usage example in the README.md would be great.

**Comment by zchee** [comment]
@justinmk No! always hand writing!! lol

**Comment by justinmk** [comment]
apiimp is supposed to be auto-generated. https://github.com/neovim/go-client/blob/805675898d92f6fc53018e83366ec9e58205c8ff/nvim/apitool.go#L3

**Comment by zchee** [comment]
Ah, but write API boilerplate to `apidef.go`, and run `go generate`. then updated `apiimp.go`. It's development flow.
If you said means doc comment, arg or etc, those are almost hand written.

you said which meaning?

**Comment by justinmk** [comment]
So, the version of `apiimp.go` that you have posted here, is auto-generated?

**Comment by zchee** [comment]
Ah, I see. you said means developer flow?

If so, I'll create `CONTRIBUTING.md` or write flow to readme.

**Comment by justinmk** [comment]
Just README.md is enough (1 or 2 lines, plus example).

**Comment by zchee** [comment]
> So, the version of apiimp.go that you have posted here, is auto-generated?

Yes, correct. `apiimp.go` generated based by `apidef.go`.

**Comment by zchee** [comment]
> Just README.md is enough (1 or 2 lines, plus example).

I see, will do.
But I don't native English speaker, pls pointed out sentence or etc when I send PR.

**Comment by zchee** [comment]
@justinmk
I have a suggestion, go-client has been implemented all now latest Neovim APIs.
I said before, Go developer(and Go core team) suggest use semver.
So, I think it's good timing to release 1.0.0, what do you think?

**Pull request merged**
