### PR TITLE
Update Neovim API to neovim/neovim@ddf0bfa

### PR DESCRIPTION
**Pull request by zchee**
Update Neovim API to neovim/neovim@ddf0bfa.
Added:

- nvim_buf_get_keymap
- nvim_get_keymap
- nvim_get_hl_by_id
- nvim_get_hl_by_name

### CODE REVIEW

**Comment by garyburd** [comment]
Should these methods return a struct type instead of a map[string]interface{}?  The struct type is more convenient to use then a map. The struct types can be derived from the code in  mapblock_fill_dict and hlattrs2dict.

**Comment by zchee** [comment]
@garyburd Ah, I see. I'll write `mapblock_fill_dict` and `hlattrs2dict` struct type, and rewrite this pull request.
Thanks for advice :)

**Comment by justinmk** [comment]
> Should these methods return a struct type instead of a map[string]interface{}?

Not sure if it matters, but please note `:help api-contract` :

> New items may be ADDED to map/list parameters/results of functions and events. 

Clients should be forward-compatible with the possibility of new map/list items being added in future versions of Nvim.

**Comment by garyburd** [comment]
re: compatibility

Because the  msgpack struct decoder ignores unknown map keys, the use of struct results here is forward compatible.

**Comment by garyburd** [comment]
The function `hlattrs2dict` only adds non-default values to the dictionary.  There are two ways to handle this on the Go side.  The first is to use pointers in all struct fields:

```
type HLAttrs struct {
   Bold *bool
   Underline *bool
   Undercurl *bool
   Italic *bool
   Reverse *bool
   Foreground *int 
   Background *int
   Special *int
}
```
If the field value is nil, then the value is not present in the dictionary.  This is the easiest to implement, but it is inconvenient to use (`bold := x.Bold != nil && x.Bold`).

The second option is to add knowledge of the defaults to the Go side: the missing bool values are always false and the missing int values are always -1.

```
type HLAttrs struct {
   Bold bool
   Underline bool
   Undercurl bool
   Italic bool
   Reverse bool
   Foreground int   // -1 indicates not set
   Background int // -1 indicates not set
   Special int // -1 indicates not set
}
```
This is much easier to use, but requires a custom decoder to set the ints to -1 by default. 

I lean towards the second approach.

**Comment by garyburd** [comment]
I'll update the msgpack decoder to support a new struct tag called "empty".  On decode, all fields will be set to the empty value.  On encode, omitempty will use the empty value instead of the zero value when skipping fields.  With this change, the -1 issue above is easily handled by adding three field tags.

**Comment by garyburd** [comment]
I added the empty field tag feature in 11df26a7bb73a1694f64cb668d689402630a50ff.  With this feature, the highlight attribute struct is:

type HLAttr struct {
	Bold       bool `msgpack:"bold"`
	Underline  bool `msgpack:"underline"`
	Undercurl  bool `msgpack:"undercurl"`
	Italic     bool `msgpack:"italic"`
	Reverse    bool `msgpack:"reverse"`
	Foreground int  `msgpack":foreground" empty:"-1"`
	Background int  `msgpack":background" empty:"-1"`
	Speical    int  `msgpack":special" empty:"-1"`
}

Let me know if you want me to finish the work o this PR.

**Comment by zchee** [comment]
@garyburd Wow, thanks for added `empty` tag feature. I'll use it and fix PR later.

**Comment by garyburd** [comment]
See #31 31

**Comment by garyburd** [comment]
I finished this in 1c2696a88048c01a46c9c6be486ee0ded23beb91.

**Comment by zchee** [comment]
@garyburd Sorry for the late reply. And thanks for implement it :)

**Pull request closed without merging**
