### PR TITLE
If CommandCompletionArgs.CursorPosString is a string, and not at int,

### PR DESCRIPTION
**Pull request by WhoIsSethDaniel**
msgpack consistently errors out saying it cannot convert an 'int to a
string'. If you change it to an int it works as expected.

### CODE REVIEW

**Comment by zchee** [comment]
@WhoIsSethDaniel sorry for late, I'll check and test, but currently go-client have CI problem. I want to fix CI first, Could you waiting?

**Comment by WhoIsSethDaniel** [comment]
> @WhoIsSethDaniel sorry for late, I'll check and test, but currently go-client have CI problem. I want to fix CI first, Could you waiting?

Yes I can wait

**Comment by zchee** [comment]
@WhoIsSethDaniel fixed CI. Could you write a test case as much as possible?

**Comment by zchee** [comment]
@WhoIsSethDaniel never mind. I found it type is int in Neovim doc `:help`.
Will merge and I'll write testcase.

**Review by zchee — APPROVED** [review]

**Pull request merged**
