### PR TITLE
Add license header

### PR DESCRIPTION
**Pull request by zchee**
Add license header to `apiimp.go` template.

In the Apache license _**"APPENDIX: HOW TO APPLY THE APACHE LICENSE TO YOUR WORK"**_  section,

> The text should be enclosed in the appropriate comment syntax for the file format.

Use `2016` year, Because, in the Go language, it is customary not to change it after the year you commit the file.

### CODE REVIEW

**Comment by justinmk** [comment]
There's little reason to put the license at the top of any file. It's only needed in one file, the LICENSE file, at the top of the project tree.

> Use 2016 year, Because, in the Go language, it is customary not to change it after the year you commit the file.

Yes, it's unnecessary and silly ritual to "update the year". I don't know why people do that.

**Comment by zchee** [comment]
@justinmk

> I'd suggest to remove the license from the top of all files, there is no legal reason for that. Only the LICENSE file is needed.

Yeah I know, Apache license said _should_. This commit is just in case.
So, I should close this pull request? up to you.

Off topic, I want hear your opinions.
If when adding new implementation with new file, should I also not add license header cooment? If not, the author name is I think would be better to "The go-client Authors." or "Neovim Authors" etc. because garyburd has been not a maintainers.
What do you think?

> Yes, it's unnecessary and silly ritual to "update the year". I don't know why people do that.

Totally agreed :P

**Comment by zchee** [comment]
Also,

> I'd suggest to remove the license from the top of all files

If you want to it, I'll send another pull request that's remove license cooment from all go files.

**Comment by justinmk** [comment]
> If when adding new implementation with new file, should I also not add license header cooment?

Don't need license header. 

Gary still has copyright on most of the code, I wouldn't bother changing it to "go client authors".

**Comment by zchee** [comment]
@justinmk

I see, I said

> If when adding new implementation with new file, should I also not add license header cooment? **If not,** ...

So my concern was resolved.

You reactioned my comment. I will send pull request that remove license header from all files.

**Comment by zchee** [comment]
close.

**Pull request closed without merging**
